services:
  pg_db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  php_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pg_db
    ports:
      - "80:80"
